const env = process.env

module.exports = { 
    POSTGRES_DB_USER: env.POSTGRES_DB_USER,
    POSTGRES_DB_HOST: env.POSTGRES_DB_HOST,
    POSTGRES_DB_PORT: env.POSTGRES_DB_PORT,
    POSTGRES_DB: env.POSTGRES_DB,
    POSTGRES_HOST_AUTH_METHOD: env.POSTGRES_HOST_AUTH_METHOD,
    PHANTOM_RPC_URL: env.PHANTOM_RPC_URL,
    PHANTOM_RECEPIENT_ADDRESS: env.PHANTOM_RECEPIENT_ADDRESS
} 